server:
  port: 8989

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  profiles:
    active: dev

kinghy:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: kinghy
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: kinghy
    user-ttl: 7200000
    user-token-name: Authorization